name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
    - main

jobs:
  build-and-push:
    # only run on the source repo
    if: github.event.pull_request.head.repo.full_name == 'cabinetoffice/gsg-guidance'
    
    environment: deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Install Cloud Foundry CLI
      env:
        CF_CLI_VERSION: 7.1.0
        CF_CLI_URL: https://packages.cloudfoundry.org/stable?release=linux64-binary&version=
      run: |
        curl -sL "${CF_CLI_URL}${CF_CLI_VERSION}" | sudo tar -zx -C /usr/local/bin
        cf7 version

    - name: Build docs with middleman
      run: bundle exec middleman build

    - name: Push to GOV.UK PaaS
      env:
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      run: |
        cf api https://api.london.cloud.service.gov.uk
        cf auth
        cf target -o cabinet-office-gsg -s gsg-guidance
        cf push security-docs --strategy rolling
